image: codefresh/github-pull-request
tag: master
version: 0.1.0
description: Creates GitHub pull request
keywords:
  - docker
  - github
  - pull-request
home: https://github.com/codefresh-io/cf-github-pull-request
sources:
  - https://github.com/codefresh-io/cf-github-pull-request
maintainers: # (optional)
  - name: Nick Sakovich
    email: nick.sakovich@codefresh.io
icon: https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png
envs:
  - name: GITHUB_TOKEN
    type: required
    description: Token for access to GitHub
  - name: HEAD
    type: required
    description: The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace head with a user like this: username:branch
  - name: BASE
    type: required
    description: The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository.
  - name: TITLE
    type: required
    description: The title of the pull request
