tag: 0.0.1
version: 0.1.0
description: Deploy an application on dcos cluster
keywords:
  - dcos
  - deploy
  - deployment
 +home: https://github.com/codefresh-io/cf-deploy-dcos
 +sources:
 +  - https://github.com/codefresh-io/cf-deploy-dcos
 +maintainers: # (optional)
 +  - name: Eugene Semirski
 +    email: eugene@codefresh.io
 +icon: https://avatars0.githubusercontent.com/u/29493517?v=4&s=400
 +envs:
 +  - name: ENV_NAME
 +    type: required
 +    description: Some description
